# Generated by Django 5.0.4 on 2024-05-16 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0006_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', help_text='The name of the general setting', max_length=254, verbose_name='Name')),
                ('percentage', models.FloatField(default='50', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
                'ordering': ('order',),
            },
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='SkillLeft',
        ),
    ]
