# Generated by Django 5.0.4 on 2024-05-16 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0007_skillright_rename_skill_skillleft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillleft',
            options={'ordering': ('order',), 'verbose_name': 'Skill Left', 'verbose_name_plural': 'Skills Left'},
        ),
        migrations.AlterModelOptions(
            name='skillright',
            options={'ordering': ('order',), 'verbose_name': 'Skill Right', 'verbose_name_plural': 'Skills Right'},
        ),
        migrations.AlterField(
            model_name='skillleft',
            name='percentage',
            field=models.IntegerField(default='50', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='skillright',
            name='percentage',
            field=models.IntegerField(default='50', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage'),
        ),
    ]
