# Generated by Django 5.0.4 on 2024-05-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0009_experienceleft'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceLeft',
            new_name='Experience',
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('start_date',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
