# Generated by Django 5.0.4 on 2024-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0010_rename_experienceleft_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_summary',
            field=models.TextField(blank=True, default='', max_length=20000, verbose_name='Job Summary'),
        ),
    ]
