# Generated by Django 5.0.4 on 2024-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0012_education_alter_experience_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-start_date',), 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AddField(
            model_name='education',
            name='education_summary',
            field=models.TextField(blank=True, default='', max_length=20000, verbose_name='Education Summary'),
        ),
        migrations.AlterField(
            model_name='education',
            name='department',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Department'),
        ),
    ]
