# Generated by Django 5.0.4 on 2024-05-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0013_alter_education_options_education_education_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End Date'),
        ),
    ]
