# Generated by Django 5.0.4 on 2024-05-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0014_alter_education_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('community_tag', models.CharField(blank=True, default='', max_length=254, verbose_name='Community Tag')),
                ('community_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Community Name')),
                ('community_place', models.CharField(blank=True, default='', max_length=254, verbose_name='Community Place')),
                ('community_start_date', models.DateField(verbose_name='Community Start Date')),
                ('community_end_date', models.DateField(blank=True, default=None, null=True, verbose_name='Community End Date')),
            ],
            options={
                'verbose_name': 'My Community',
                'verbose_name_plural': 'My Communities',
                'ordering': ('community_name',),
            },
        ),
    ]
