# Generated by Django 5.0.4 on 2024-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0015_my_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('certificate_name', models.CharField(blank=True, default='', help_text='The name of the general setting', max_length=254, verbose_name='Name')),
                ('certificate_description', models.CharField(blank=True, default='', help_text='The description of the general setting', max_length=254, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'My Community',
                'verbose_name_plural': 'My Certificates',
                'ordering': ('certificate_name',),
            },
        ),
    ]
