# Generated by Django 5.0.4 on 2024-05-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0017_certificate_certificate_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('name',), 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_tag',
        ),
        migrations.AddField(
            model_name='certificate',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=20000, verbose_name='Parameter'),
        ),
    ]
